1.  http://127.0.0.1/techunity_erp_v2/purchase/indent_list : DataTables warning: JSON data from server could not be parsed. This is caused by a JSON formatting error.
2. Exception E:\MAMP\htdocs\techunity_erp_v2\purchase\app\indent_list\index.php
mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line

3. https://techunity.live/qc_v2/purchase/indent_list
UNApproval indent is not working

4. http://127.0.0.1/techunity_erp_v2/purchase/po_quotation_list_new
code update in Request For Quotation

5. http://127.0.0.1/techunity_erp_v2/purchase/po_quotation_list_new
Error: Undefined constant "PO_QUOTATION_PRINT"